trigger:
  batch: true
  branches:
    include:
      - develop
      - release

resources:
  repositories:
    - repository: templates
      type: git
      name: LFM.Pipelines

stages:
  - stage: Build
    displayName: Build
    jobs:
      - job: build_nuget
        template: build.yml
