trigger:
  batch: true
  branches:
    include:
      - develop
      - release

stages:
  - stage: Build NuGet
    displayName: Build
    jobs:
      - template: build.yml

  - stage: Build application
    displayName: Build application
    jobs:
      - template: build.yml@LFM.Pipelines
        parameters:
          buildType: application
