trigger:
  batch: true
  branches:
    include:
      - develop
      - release

resources:
  repositories:
    - repository: templates
      type: git
      name: LFM.Pipelines

stages:
  - stage: Build NuGet
    displayName: Build
    jobs:
      - template: build.yml

  - stage: Build application
    displayName: Build application
    jobs:
      - template: build.yml@templates
        parameters:
          applicationName: application
