parameters:
  - name: RunTests
    type: boolean
    default: true

trigger:
  batch: true
  branches:
    include:
      - develop
      - release

resources:
  repositories:
    - repository: templates
      type: git
      name: LFM.Pipelines

stages:
  - stage: Build
    displayName: Build
    jobs:
      - template: build.yml

      - template: build.yml@templates
        parameters:
          applicationName: "lfm-authorization"
          dockerfile: "LFM.Authorization/Dockerfile"

  - stage: Test
    displayName: Test
    condition: and(succeeded(), or(eq(variables['Build.Reason'], 'PullRequest'), eq(${{ parameters.RunTests }}, true)))
    jobs:
      - template: security-scan.yml@templates
        parameters:
          organization: lifemanager
          projectKey: ThijmenBrand_LFM.Authorization
          projectName: LFM.Authorization
