name: Build and deploy LFM.Authorization

env:
  GITHUB_NAMESPACE: ThijmenBrand-LifeManager
  GITHUB_USERNAME: ThijmenBrand
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE: LFM.Authorization/LFM.Authorization.sln
  PROJECT_FILE: LFM.Authorization/LFM.Authorization.AspNetCore/LFM.Authorization.AspNetCore.csproj

on:
  workflow_dispatch:
    inputs:
      publish-package:
        description: "Publish package"
        default: false
        type: boolean
      release:
        description: "Release app"
        default: false
        type: boolean
  pull_request:
    branches:
      - develop
      - release
  push:
    branches:
      - develop
      - release

jobs:
  build:
    if: inputs.publish-package == true || github.event_name == 'push' || github.event_name == 'pull_request'
    name: Build and publish packages
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-package.yml@main
    with:
      solution-file: LFM.Authorization/LFM.Authorization.sln
      project-file: LFM.Authorization/LFM.Authorization.AspNetCore/LFM.Authorization.AspNetCore.csproj
      build-configuration: Release
      dotnet-version: 8.0.x
    secrets: inherit

  test:
    needs: build
    if: github.event_name == 'pull_request' && (github.base_ref == 'develop' || github.base_ref == 'release')
    name: Build and test application
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-and-test.yml@main
    with:
      dotnet-version: 8.0.x
      solution-file: LFM.Authorization/LFM.Authorization.sln
      build-configuration: Release
    secrets: inherit

  automatic-deploy:
    needs: [build, test]
    if: inputs.release == false && github.event_name == 'push'
    name: Automatic deploy to Env
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-docker-image.yml@main
    with:
      environment: develop
      project-path: LFM.Authorization
      dockerfile-path: |-
        api.Dockerfile
        endpoint.Dockerfile
    secrets: inherit

  manual-deploy:
    needs: [build]
    if: inputs.release == true
    name: Manual deploy to env
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/build-docker-image.yml@main
    with:
      environment: develop
      project-path: LFM.Authorization
      dockerfile-path: |-
        api.Dockerfile
        endpoint.Dockerfile
    secrets: inherit
