name: Build and deploy LFM.Authorization

env:
  GITHUB_NAMESPACE: ThijmenBrand-LifeManager
  GITHUB_USERNAME: ThijmenBrand
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE: LFM.Authorization/LFM.Authorization.sln
  PROJECT_FILE: LFM.Authorization/LFM.Authorization.AspNetCore/LFM.Authorization.AspNetCore.csproj

on:
  workflow_dispatch:
    inputs:
      release-dev:
        description: "Release app to D"
        default: false
        type: boolean
  pull_request:
    branches:
      - develop
      - release
  push:
    branches:
      - develop
      - release
  release:
    types: [published]

permissions:
  actions: read

jobs:
  main:
    name: A test
    uses: ThijmenBrand-LifeManager/LFM.Pipelines/.github/workflows/main.yml@main
    with:
      project-path: LFM.Authorization
      solution-file: LFM.Authorization/LFM.Authorization.sln
      package-path: |-
        LFM.Authorization/LFM.Authorization.AspNetCore/LFM.Authorization.AspNetCore.csproj
      dockerfile-path: |-
        api.Dockerfile
        endpoint.Dockerfile
      force-release-dev: ${{ inputs.release-dev || false }}
      app-name: LFM.Authorization
    secrets: inherit
