name: Build and deploy LFM.Authorization

env:
  GITHUB_NAMESPACE: ThijmenBrand-LifeManager
  GITHUB_USERNAME: ThijmenBrand
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE: LFM.Authorization/LFM.Authorization.sln
  PROJECT_FILE: LFM.Authorization/LFM.Authorization.AspNetCore/LFM.Authorization.AspNetCore.csproj

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - release

jobs:
  build-and-publish-package:
    uses: ./.github/workflows/build-package.yml
    with:
      solution-file: $SOLUTION_FILE
      project-file: $PROJECT_FILE
      build-configuration: $BUILD_CONFIGURATION
      dotnet-version: 8.0.x
    secrets: inherit
